.gitattributes

SMT is currently detected as the main language when it should probably be Python or C++. This commit marks the SMT files as generated so that [Linguist](https://github.com/github-linguist/linguist) recomputes the statistics. It will only be visible a little bit after this is merged unfortunately.

.gitattributes: Ignore generated SMT files in GitHub statistics

---

README.md
requirements.txt

The `lib_reg_bounds_tracking` package also needs to be installed before running verification.

README: Fix missing step in instructions

---

bpf-verification/src/wf_soundness.py

This pull request parallelizes the execution of the gen verification for each instruction using the multiprocessing Python module. See commits for details.
I tested the speed up on an AMD Ryzen 9 3950X 16-Core processor with hyperthreading enabled (32 logical processors). On Linux v5.9 (65 sro violations), the runtime went from ~19h to 4h. On Linux v6.0 (0 sro violations), it went from 41h+ (interrupted) to ~18h.

Parallelize `gen` verification

---

.gitattributes

The `.gitattributes` syntax for the Linguist override is incorrect. Selecting all in a directory requires `/**`. I got confused between the different syntaxes git and GitHub have for directories.
I tested it locally this time by installing Linguist:
$ gem install github-linguist
$ github-linguist
57.00%  178040     Python
37.30%  116499     C++
2.89%   9037       Shell
2.81%   8762       CMake
Fixes: 546421f31dea (".gitattributes: Ignore generated SMT files in GitHub statistics")

.gitattributes: Fix syntax for directory

---

llvm-to-smt/generate_encodings.py
llvm-to-smt/llvm-passes/ForceFunctionEarlyExit/config.json
llvm-to-smt/llvm-passes/InlineFunctionCalls/InlineFunctionCalls.hpp
llvm-to-smt/llvm-passes/LLVMToSMT/BitvecHelper.cpp
llvm-to-smt/llvm-passes/LLVMToSMT/BitvecHelper.hpp
llvm-to-smt/llvm-passes/LLVMToSMT/FunctionEncoder.cpp
llvm-to-smt/llvm-passes/LLVMToSMT/FunctionEncoder.hpp
llvm-to-smt/llvm-passes/LowerFunnelShifts/CMakeLists.txt
llvm-to-smt/llvm-passes/LowerFunnelShifts/LowerFunnelShifts.cpp
llvm-to-smt/llvm-passes/LowerFunnelShifts/LowerFunnelShifts.hpp
llvm-to-smt/llvm-passes/inline_verifier_func.sh
llvm-to-smt/llvm-passes/lower_funnel_shifts.sh
llvm-to-smt/run_llvm_passes.py
llvm-to-smt/tests/select_on_pointers.ll
llvm-to-smt/wrappers.py

1. Handle select instructions that select on pointer types (e.g. `struct.bpf_reg_state`). This involves handling loads from and stores to pointers derived from the result of such a select instruction. 
```
%select_on_ptrs = select i1 %select_value, %struct.bpf_reg_state* %src_reg, 
%struct.bpf_reg_state* %dst_reg
%gep_ptr_load = getelementptr %bpf_reg_state, %bpf_reg_state* %select_on_ptrs, i64 0, i32 0
%load_value = load i32, i32* %gep_ptr_load, align 8
%gep_ptr_store = getelementptr %bpf_reg_state, %bpf_reg_state* %select_on_ptrs, i64 0, i32 5
store i64 0, i64* %gep_ptr_store, align 8
```
2. Handle loads and stores to pointers derived from phi instructions that chooses on pointer types (e.g. `struct.bpf_reg_state`). Again, this involves handling loads from and stores to pointers derived …

llvm-to-smt: handle select on pointers and phi on pointers

---

llvm-to-smt/generate_encodings.py

While implementing a CI workflow for llvm-to-smt, I noticed that the Python script doesn't return with a non-zero code in case errors where found while generating the encodings. This commit fixes it.

llvm-to-smt: Exit with non-zero code in case of errors

---

.gitattributes

The repository with all the generated SMT code was moved so we need to update .gitattributes as well.
Fixes: 989c5b3828 ("Move bpf encodings to top-level directory")

.gitattributes: Fix GitHub language statistics

---

.github/workflows/bpf-verification.yaml

This commit adds a GitHub CI test for `bpf_alu_jmp_synthesis.py` and related logic. It is currently limited to the v5.9 kernel as newer kernels easily take hours to verify a single instruction (cf. https://github.com/bpfverif/agni/issues/13). It's also limited to two instructions (one jump, one ALU) among the fatest to verify. Total verification time appears to be <5min.
This workflow will run for pull request (when opened or updated) and for all pushes to main. If several commits are pushed to main at the same time, it should only run for the latest commit of the batch.
There is a lot that can be improved: running this only when `bpf-verification/` is modified, covering more kernels and instructions, checking the results, etc. I chose to start with something small we can improve later …

workflows: CI for the verification step

---

.github/workflows/llvm-to-smt.yml

This commit adds a GitHub CI workflow for `generate_encodings.py` and associated logic. Total runtime is below three minutes.
This workflow will run for pull request (when opened or updated) and for all pushes to main. If several commits are pushed to main at the same time, it should only run for the latest commit of the batch.
It currently doesn't support running against latest as that will require updating the LLVM dependency. The resulting encodings are also not checked yet. It simply verifies that the script doesn't error out.
Updates https://github.com/bpfverif/agni/issues/16.

workflows: Initial CI for the LLVM-to-SMT step

---

llvm-to-smt/generate_encodings.py
llvm-to-smt/run_llvm_passes.py
llvm-to-smt/wrappers.py

This series of commits: 
1. Allows generating the 32-bit and 64-bit op encodings separately when using `--separate-op`
2. Moves the logging for each "op" into a separate log file created in the op directory.
3. Fixes a minor nit in the wrapper function names.

Update generate encodings scripts for better logging and encoding generation

---

.github/workflows/llvm-to-smt.yml
llvm-to-smt/generate_encodings.py
llvm-to-smt/llvm-passes/ForceFunctionEarlyExit/CMakeLists.txt
llvm-to-smt/llvm-passes/InlineFunctionCalls/CMakeLists.txt
llvm-to-smt/llvm-passes/InlineFunctionCalls/InlineFunctionCalls.cpp
llvm-to-smt/llvm-passes/LLVMToSMT/CMakeLists.txt
llvm-to-smt/llvm-passes/LowerFunnelShifts/CMakeLists.txt
llvm-to-smt/llvm-passes/PromoteMemcpy/CMakeLists.txt
llvm-to-smt/llvm-passes/PromoteMemcpy/PromoteMemcpy.cpp
llvm-to-smt/llvm-passes/RemoveFunctionCalls/CMakeLists.txt
llvm-to-smt/run_llvm_passes.py

Since Linux commit [9c1b86f8ce04e](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=9c1b86f8ce04e) ("kbuild: raise the minimum supported version of LLVM to 13.0.1"), which is `v6.9-rc1~106^2~38`, the kernel requires LLVM 13.0.1 to compile.
We therefore need to upgrade our LLVM dependency to be able to run Agni against latest kernels. Upgrading past LLVM 15 is a lot more work because typed pointers were replaced by opaque pointers, but we should be able to upgrade to LLVM 14.
Two changes are needed in the sources to adapt to changes in the LLVM API:
- `sys::fs::F_None` was renamed to `sys::fs::OF_None`.
- The handy `Builder.CreateLoad` functions that take only two arguments have been removed.
Fixes: https://github.com/bpfverif/agni/issues/26.

llvm-to-smt: Use LLVM 14.0.0

---

.github/workflows/llvm-to-smt.yml

Cover the latest linus and bpf-next trees in the LLVM-to-SMT workflow.

workflows/llvm-to-smt: Cover more kernels

---

.github/workflows/llvm-to-smt.yml

Only BPF_AND is currently covered. The encoding generation for jump instructions differs quite a bit, so we should cover it as well.

workflows/llvm-to-smt: Cover BPF_JSLT

---

llvm-to-smt/generate_encodings.py
llvm-to-smt/wrappers.py

This commit updates the wrappers for v6.10-rc5 and above, specifically including the idea in commit [1].
While this doesn't affect the encodings for BPF_JMP_REG instructions, it will be useful when addressing
BPF_JMP_IMM types, and addressing [2].
[1]: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=92424801261d1564a0bb759da3cf3ccd69fdf5a2
[2]: https://github.com/bpfverif/agni/issues/40

llvm-to-smt: wrappers for v6.10

---

.github/workflows/end-to-end.yaml

This new workflow will run on a schedule to validate the linus and bpf-next trees. It will both generate the encodings for those trees and run the verification.
Successful run: https://github.com/bpfverif/agni/actions/runs/10374722808. To test it, I changed the triggers so that it triggers on a PR push.
Fixes: https://github.com/bpfverif/agni/issues/16.

workflows: End-to-end test

---

.github/workflows/bpf-verification.yaml
.github/workflows/llvm-to-smt.yml

First commit removes coverage for bpf-next and linus from the pull request workflows. Second commit ensures we always upload artifacts. See commit descriptions for details.

workflows: Cleanup

---

.github/workflows/end-to-end.yaml
llvm-to-smt/llvm-passes/LLVMToSMT/FunctionEncoder.cpp
llvm-to-smt/llvm-passes/LLVMToSMT/FunctionEncoder.hpp

This commits support for llvm add/sub intrinsics with overflow detection: llvm.sadd.with.overflow.*, llvm.uadd.with.overflow.*, llvm.ssub.with.overflow.*, llvm.usub.with.overflow.* . It also adds limited support for extractvalue instructions to support the intrinsics. This is needed in order to support BPF_ADD and BPF_SUB instructions in v6.10 [1].
The return type of the add with overflow intrinsic is an aggregate type. The types are automatically inferred and appropriate sized bitvectors are used (i32/i64/any other size) in the formula. This commit also adds support for extractvalue instructions, that typically occur *after* the intrinsic call instructions.
See the commit message and comments for details. 
[1]: https://github.com/bpfverif/agni/issues/44

llvm-to-smt: Support llvm.*.with.overflow.* intrinsics and extractvalue

---

llvm-to-smt/llvm-passes/LLVMToSMT/FunctionEncoder.cpp
llvm-to-smt/llvm-passes/LLVMToSMT/FunctionEncoder.hpp

In the future there could be new instructions which we do not support. To that end, there should be at least one function that iterates over all the instructions in llvm IR, to make sure we aren't missing anything. These commits address that. This is more of a nice-to-have, and is not a problem currently.  Commits have more details.

Explicit insn coverage

---

.github/workflows/end-to-end.yaml

Successful run can be seen here: https://github.com/bpfverif/agni/actions/runs/10539785106.

workflows: Cover bpf tree in end-to-end test

---

llvm-to-smt/llvm-passes/LLVMToSMT/FunctionEncoder.cpp
llvm-to-smt/llvm-passes/LLVMToSMT/FunctionEncoder.hpp

Address store to phi ptrs, that should address https://github.com/bpfverif/agni/issues/39. 
The first two commits are mostly refactoring in preparation for the third commit. The third commit handles store to phi pointers, by modifying the existing handleStoreToPhiPtr() function to handle stores to only a specific type of phi pointer.
Such a phi pointer instruction chooses one of two or more pointers to store at, depending on the basic block that was taken to arrive at the phi pointer instruction.
Previously handleStoreToPhiPtr() addressed a more complicated case: store instruction that stores to a phi pointer that chooses between two pointers, which themselves were derived by indexing into another phi pointer. With llvm-14 it seems we don't need to handle this case, and instead need to …

Store to phi

---

llvm-to-smt/generate_encodings.py

Since llvm-to-smt does not support llvm.memset intrinsic calls, we delete memset() calls in verifier.c using the function mark_reg_unknown_memset_remove() in generate_encodings.py
However, in kernel versions <5.5, the memset calls in __mark_reg_unknown() were not being deleted correctly, leading to an error when we attempted to generate encodings https://github.com/bpfverif/agni/issues/10
This commit fixes the error, supporting kernels before 5.5 as well.

llvm-to-smt: Fix encodings generation for kernels <5.5

---

llvm-to-smt/generate_encodings.py

In order to compare two encodings for equivalent input-output behavior, we need the pairs of encodings to use different bitvectors names. Currently, bitvector suffixes are hardcoded in the suffix_id field of each op in bpf_ops. This commit allows overriding the default bitvector suffixes by providing a flag that replaces the hardcoded_suffix_id with hardcoded_suffix_id + 1000.

generate-encodings: Add option for overriding bitvector suffixes

---

llvm-to-smt/llvm-passes/LLVMToSMT/FunctionEncoder.cpp
llvm-to-smt/llvm-passes/LLVMToSMT/FunctionEncoder.hpp

In LLVMToSMT, we don’t support generating encodings for abstract operator functions with backward edges, i.e., functions whose CFG is not a DAG. This commit introduces a check to allow LLVMToSMT to exit early if the CFG of the function being encoded is not a DAG.
Previously, LLVMToSMT could generate incorrect encodings silently for abstract operators with backward edges. By adding this check, we make the failure explicit, preventing silent errors.
As a side note, in a prior kernel commit [1], we updated regs_refine_cond_op() to remove a backward edge from the CFG of abstract operators for JUMP instructions.
[1] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=4c2a26fc80

llvm-to-smt: Exit early if function is not a DAG

---

.github/workflows/bpf-verification.yaml
.github/workflows/end-to-end.yaml
.github/workflows/llvm-to-smt.yml

Commits 18b7513, 285dc20, and a30260d incorrectly used `continue-on-error` in our three workflows causing all job failures to be ignored at the workflow level. Thus, workflow runs would be reported as successful even when all their jobs were failing.
This commit fixes that by using the intended `strategy.fail-fast` [1] configuration instead. This configuration, when set to false, will prevent a single job failure from interrupting the whole workflow. Instead, other jobs will continue running and the workflow run will then be correctly reported as failed. The intent is simply to gather information on all jobs before failing the workflow.
1 - https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast Fixes: …

workflows: Fix error reporting for the workflow runs

---

.github/workflows/bpf-verification.yaml
.github/workflows/end-to-end.yaml
.github/workflows/llvm-to-smt.yml

This should fix the LLVM-to-SMT and the End-to-End workflows. See commits for details.
Updates: https://github.com/bpfverif/agni/issues/68.

workflows: Fix v5.x compilation errors

---

.github/workflows/end-to-end.yaml

This will allow us to trigger the end-to-end workflow manually, if we ever want to run it without waiting 24h.

workflows: Add manual trigger to end-to-end workflow

---

bpf-verification/lib_reg_bounds_tracking/lib_reg_bounds_tracking.py
bpf-verification/src/bpf_alu_jmp_synthesis.py
llvm-to-smt/generate_encodings.py
llvm-to-smt/llvm-passes/LLVMToSMT/FunctionEncoder.cpp
llvm-to-smt/llvm-passes/LLVMToSMT/FunctionEncoder.hpp

In order to support BPF_JSET, we will have to add support for the llvm.ctpop intrinsic, which is does a population count of 1 bits in an integer, for example:
%o = call i4 @llvm.ctpop.i4(i4 %i)
See the first commit message for the details of generating encodings with llvm.ctpop. I was able to generate encodings for BPF_JSET, BPF_JSET_32.
The second commit adds support for BPF_JSET to bpf_alu_jmp_synthesis.py and lib_reg_bounds_tracking.py.

llvm-to-smt: Support llvm ctpop intrinsics, BPF_JSET

---

.github/workflows/end-to-end.yaml

Since we merged commit [`5dbb19b16ac4`](https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=5dbb19b16ac4) upstream, to verify `BPF_SYNC`, Agni went from 1h30 to 4h30-5h. The workflow is therefore now timing out. As a short-term measure, let's increase the timeout to 6h.
A successful run is visible here: https://github.com/bpfverif/agni/actions/runs/16652987534?pr=77.

workflows/e2e: Increase timeout

---

llvm-to-smt/llvm-passes/LLVMToSMT/FunctionEncoder.cpp
llvm-to-smt/llvm-passes/LLVMToSMT/FunctionEncoder.hpp

This commit adds support for load instructions that load from a phi pointer (of single value type). For example:
...
lend:
%umin_phi = phi i64* [ %umax1, %ltrue ], [ %umax2, %lfalse ]
%umin_phi_load = load i64, i64* %umin_phi, align 8
Here, the phi instruction chooses between two GEP pointers that were defined previously. The load instruction loads the value that the phi instruction points to.
To handle such a case, we simply set the loaded value's (umin_phi_load) bitvector ( umin_phi_load_bv) depending on the path conditions that the phi instruction were based on.
(=> lfalse_lend (= umin_phi_load_bv dst_reg_7_bv)) (=> ltrue_lend (= umin_phi_load_bv src_reg_7_bv))
Note that this commit only handles cases where the phi pointer is a single value type pointer, e.g. an i32* or an i64*. …

llvm-to-smt: Handle load from phi pointers
